[providers]
python = "3.11"

[variables]
PYTHON_VERSION = "3.11.9"

[phases.setup]
nixPkgs = ["python311", "pip", "postgresql"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r ../requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate --noinput && gunicorn gestion_clinica.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"

